project:
    name: fru-tracker
    module: github.com/example/fru-tracker
    created: 2026-02-11T10:03:39.948195-08:00
features:
    validation:
        enabled: true
        mode: strict
    events:
        enabled: true
        bus_type: memory
    conditional:
        enabled: true
        etag_algorithm: sha256
    auth:
        enabled: false
    storage:
        enabled: true
        type: file
        db_driver: sqlite3
    reconciliation:
        enabled: true
        worker_count: 5
        requeue_delay: 5
generation:
    handlers: true
    storage: true
    client: true
    openapi: true
    events: true
    middleware: true
    reconciliation: true
