
// Generated by Fabrica dev
// Template: init/go.mod.tmpl
// Generated: 2025-11-13T14:01:35-08:00

module github.com/example/inventory-api

go 1.21

require (
	github.com/go-chi/chi/v5 v5.0.10
	github.com/spf13/cobra v1.7.0
	github.com/spf13/viper v1.16.0
)
