// Code generated by Fabrica dev. DO NOT EDIT.
// Template: cmd/fabrica/generate.go:generateVersionedRegistrationCode
// Generated: 2026-05-05T15:52:42Z
//
// Copyright © 2026 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT

package resources

import (
	"fmt"

	v1 "github.com/example/fru-tracker/apis/example.fabrica.dev/v1"
	"github.com/openchami/fabrica/pkg/codegen"
)

// RegisterAllResources registers all discovered resources with the generator.
// This file is auto-generated. Re-run 'fabrica generate' after adding resources.
func RegisterAllResources(gen *codegen.Generator) error {
	if err := gen.RegisterResource(&v1.Device{}); err != nil {
		return fmt.Errorf("failed to register Device: %w", err)
	}
	if err := gen.RegisterResource(&v1.DiscoverySnapshot{}); err != nil {
		return fmt.Errorf("failed to register DiscoverySnapshot: %w", err)
	}

	return nil
}
