// SPDX-FileCopyrightText: 2026 OpenCHAMI Contributors
//
// SPDX-License-Identifier: MIT

// Code generated by Fabrica dev. DO NOT EDIT.
// Template: apiversion/register.gotmpl
// Generated at: 2026-05-05T21:44:41+01:00

package apiversion

import (
	"github.com/openchami/fabrica/pkg/apiversion"
	"github.com/openchami/fabrica/pkg/versioning"
)

// Registry is the global API version registry
var Registry *apiversion.Registry

func init() {
	Registry = apiversion.NewRegistry()
	Registry.RegisterGroup(apiversion.Group{
		Name:           "example.fabrica.dev",
		StorageVersion: "v1",
		Spokes:         []string{"v1"},
	})
	if err := versioning.GlobalVersionRegistry.RegisterVersion("Device", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
	if err := versioning.GlobalVersionRegistry.RegisterVersion("DiscoverySnapshot", "v1", versioning.ResourceTypeInfo{
		Metadata: versioning.SchemaVersion{
			Version:   "v1",
			IsDefault: true,
		},
	}); err != nil {
		panic(err)
	}
}

// GetRegistry returns the global version registry
func GetRegistry() *apiversion.Registry {
	return Registry
}
